[install]
state = enabled

[package]
id = org_indexer_inputs
check_for_updates = false

[ui]
is_visible = false
label = org_indexer_inputs

[launcher]
author = equipe-splunk
version = 1.0.0
description = Réception S2S 9997 des forwarders
