[install]
state = enabled

[package]
id = org_all_indexes
check_for_updates = false

[ui]
is_visible = false
label = org_all_indexes

[launcher]
author = equipe-splunk
version = 1.0.0
description = Définition de tous les index (volumes, rétention) - poussé aux indexeurs par le CM
