[install]
state = enabled

[package]
id = org_all_indexes_search
check_for_updates = false

[ui]
is_visible = false
label = org_all_indexes_search

[launcher]
author = equipe-splunk
version = 1.0.0
description = Liste des index côté recherche (autocomplétion, rôles)
