# Déployé par le Deployment Server sur la server class "linux_servers"
[monitor:///var/log/secure]
index = osnix
sourcetype = linux_secure
disabled = 0

[monitor:///var/log/messages]
index = osnix
sourcetype = syslog
disabled = 0
