[install]
state = enabled

[package]
id = org_soc_monitoring
check_for_updates = false

[ui]
is_visible = true
label = org_soc_monitoring

[launcher]
author = equipe-splunk
version = 1.0.0
description = Dashboards et alertes de supervision de la plateforme et de l'ingestion
