[install]
state = enabled

[package]
id = org_hec_inputs
check_for_updates = false

[ui]
is_visible = false
label = org_hec_inputs

[launcher]
author = equipe-splunk
version = 1.0.0
description = Tokens HEC - local/inputs.conf généré par Ansible depuis Vault
