---
# Inventaire du lab Proxmox.
# En mission : un inventaire par environnement (dev / rec / prod) avec la MÊME structure de groupes.
# Seules les IP, les tailles et les chemins Vault changent.
all:
  children:
    splunk:
      children:
        license_manager:
          hosts:
            cm01:
        cluster_manager:
          hosts:
            cm01:
              ansible_host: 10.10.10.10
        monitoring_console:
          hosts:
            cm01:
        indexers:
          hosts:
            idx01: { ansible_host: 10.10.10.11 }
            idx02: { ansible_host: 10.10.10.12 }
            idx03: { ansible_host: 10.10.10.13 }
        search_heads:
          hosts:
            sh01: { ansible_host: 10.10.10.21 }
            sh02: { ansible_host: 10.10.10.22 }
            sh03: { ansible_host: 10.10.10.23 }
        shc_deployer:
          hosts:
            dep01:
              ansible_host: 10.10.10.20
        deployment_server:
          hosts:
            dep01:

    ingestion:
      children:
        hec_lb:
          hosts:
            ing01:
              ansible_host: 10.10.10.30
        sc4s:
          hosts:
            ing01:
        kafka:
          hosts:
            ing01:
        logstash:
          hosts:
            ing01:

    ops:
      children:
        vault:
          hosts:
            ops01:
              ansible_host: 10.10.10.40
        artifactory:
          hosts:
            ops01:

    forwarders:
      hosts:
        lnx01:
          ansible_host: 10.10.10.50
