[install]
state = enabled

[package]
id = org_app_props
check_for_updates = false

[ui]
is_visible = false
label = org_app_props

[launcher]
author = equipe-splunk
version = 1.0.0
description = Parsing index-time des logs applicatifs
