# Rôles métier : chaque équipe ne voit que ses index (principe du moindre privilège)
[role_soc_analyst]
importRoles = user
srchIndexesAllowed = net*;os*;email;epav;epintel
srchIndexesDefault = netfw;osnix

[role_app_support]
importRoles = user
srchIndexesAllowed = app;app_heartbeat
srchIndexesDefault = app
