# Côté search heads, déclarer les index (sans données) permet l'autocomplétion
# et l'affectation aux rôles dans l'UI. Les données restent sur les indexeurs.
[app]
[app_heartbeat]
[email]
[epav]
[netfw]
[netops]
[netproxy]
[netdns]
[netauth]
[osnix]
[oswin]
[oswinsec]
[infraops]
