[install]
state = enabled

[package]
id = org_linux_inputs
check_for_updates = false

[ui]
is_visible = false
label = org_linux_inputs

[launcher]
author = equipe-splunk
version = 1.0.0
description = Collecte des logs système Linux
