[install]
state = enabled

[package]
id = org_all_forwarder_outputs
check_for_updates = false

[ui]
is_visible = false
label = org_all_forwarder_outputs

[launcher]
author = equipe-splunk
version = 1.0.0
description = Envoi des logs internes des SH vers les indexeurs - local/ généré par Ansible
